# Template Supabase config for new deployments
# Copy this to supabase/config.toml and update with your project details

project_id = "YOUR_PROJECT_ID_HERE"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
ip_version = "ipv4"

[analytics]
enabled = false

[functions.bulk-hts-analysis]
verify_jwt = true

[functions.enhanced-prediction]
verify_jwt = true

[functions.feedback]
verify_jwt = true

[functions.hts-change-tracker]
verify_jwt = true

[functions.hts-lookup]
verify_jwt = true

[functions.pdf-processor]
verify_jwt = true

[functions.semantic-analysis]
verify_jwt = true