// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcnblkynxnnlorjbrrcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjbmJsa3lueG5ubG9yamJycmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDk1MjIsImV4cCI6MjA3MTYyNTUyMn0._zItZUz_Pg6e5Wy-0SNI1Bg2iQJ5WB3yjhqTBOcW5KA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});